version: '3.9'

services:
  # Vue.js application service
  vuejs-app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"

  # Nginx service
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - vuejs-app
